import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type AgentDocument = Agent & Document;

@Schema({ timestamps: true })
export class Agent {
  @Prop({
    required: true,
    unique: true,
    uppercase: true,
    index: true,
  })
  agentCode: string;

  @Prop({ required: true })
  name: string;

  @Prop({
    required: true,
    unique: true,
    lowercase: true,
    index: true,
  })
  email: string;

  @Prop({ required: false })
  phone?: string;

  @Prop({ required: true, select: false })
  password: string;

  @Prop({
    type: [{ type: Types.ObjectId, ref: 'ParkingZone' }],
    required: false,
  })
  assignedZones?: Types.ObjectId[];

  @Prop({ required: true, default: true })
  isActive: boolean;

  // Timestamps are auto-generated by mongoose
  createdAt?: Date;
  updatedAt?: Date;
}

export const AgentSchema = SchemaFactory.createForClass(Agent);

// Compound indexes
AgentSchema.index({ isActive: 1, agentCode: 1 });
