import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type TicketTokenDocument = TicketToken & Document;

export enum TokenStatus {
  ACTIVE = 'active',
  USED = 'used',
  EXPIRED = 'expired',
  REVOKED = 'revoked',
}

@Schema({ timestamps: true })
export class TicketToken {
  @Prop({
    required: true,
    unique: true,
    index: true,
  })
  token: string;

  @Prop({
    type: Types.ObjectId,
    ref: 'Ticket',
    required: true,
    index: true,
  })
  ticketId: Types.ObjectId;

  @Prop({
    required: true,
    enum: TokenStatus,
    default: TokenStatus.ACTIVE,
    index: true,
  })
  status: TokenStatus;

  @Prop({ required: true })
  expiresAt: Date;

  @Prop({ required: false })
  usedAt?: Date;

  @Prop({ required: false })
  revokedAt?: Date;

  @Prop({ required: false })
  usedByIp?: string;

  @Prop({ required: false })
  usedByUserAgent?: string;

  // Timestamps are auto-generated by mongoose
  createdAt?: Date;
  updatedAt?: Date;
}

export const TicketTokenSchema = SchemaFactory.createForClass(TicketToken);

// TTL index to auto-delete expired tokens after 30 days
TicketTokenSchema.index(
  { expiresAt: 1 },
  { expireAfterSeconds: 30 * 24 * 60 * 60 },
);

// Compound index for finding active tokens for a ticket
TicketTokenSchema.index({ ticketId: 1, status: 1 });
