import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { LicensePlate, LicensePlateSchema } from '../../shared/license-plate';

export type TicketDocument = Ticket & Document;

export enum TicketReason {
  CAR_SABOT = 'car_sabot',
  POUND = 'pound',
}

export enum TicketStatus {
  PENDING = 'pending',
  PAID = 'paid',
  APPEALED = 'appealed',
  SABOT_REMOVED = 'sabot_removed',
  DISMISSED = 'dismissed',
  OVERDUE = 'overdue',
}

export enum PaymentMethod {
  WALLET = 'wallet',
  CARD = 'card',
  CASH = 'cash',
}

// GeoJSON Point type for position
export class GeoJsonPoint {
  type: string;
  coordinates: number[];
}

@Schema({ timestamps: true })
export class Ticket {
  /**
   * Short human-readable unique ticket number for manual entry
   * Format: 6 alphanumeric characters (e.g., A7K3M2)
   */
  @Prop({
    required: true,
    unique: true,
    uppercase: true,
    index: true,
  })
  ticketNumber: string;

  @Prop({
    type: {
      type: String,
      enum: ['Point'],
      required: true,
    },
    coordinates: {
      type: [Number],
      required: true,
    },
  })
  position: GeoJsonPoint;

  @Prop({ required: false })
  address?: string;

  @Prop({
    type: Types.ObjectId,
    ref: 'ParkingSession',
    required: false,
    index: true,
  })
  parkingSessionId?: Types.ObjectId;

  @Prop({
    type: Types.ObjectId,
    ref: 'User',
    required: false,
    index: true,
  })
  userId?: Types.ObjectId;

  @Prop({
    type: Types.ObjectId,
    ref: 'Agent',
    required: true,
    index: true,
  })
  agentId: Types.ObjectId;

  @Prop({
    type: Types.ObjectId,
    ref: 'ParkingZone',
    required: true,
    index: true,
  })
  parkingZoneId: Types.ObjectId;
  /**
   * Structured license plate data
   */
  @Prop({ type: LicensePlateSchema })
  plate?: LicensePlate;

  /**
   * @deprecated Use plate.formatted instead
   * Kept for backward compatibility and indexing
   */
  @Prop({ required: true, uppercase: true, index: true })
  licensePlate: string;

  @Prop({
    required: true,
    enum: TicketReason,
  })
  reason: TicketReason;

  @Prop({ required: true, min: 0 })
  fineAmount: number;

  @Prop({
    required: true,
    enum: TicketStatus,
    default: TicketStatus.PENDING,
    index: true,
  })
  status: TicketStatus;

  @Prop({ required: true })
  issuedAt: Date;

  @Prop({ required: true })
  dueDate: Date;

  @Prop({ required: false })
  paidAt?: Date;

  @Prop({
    required: false,
    enum: PaymentMethod,
  })
  paymentMethod?: PaymentMethod;

  @Prop({ required: false })
  notes?: string;

  @Prop({ type: [String], required: false })
  evidencePhotos?: string[];

  @Prop({ required: false })
  appealReason?: string;

  @Prop({ required: false })
  appealedAt?: Date;

  // Timestamps are auto-generated by mongoose
  createdAt?: Date;
  updatedAt?: Date;
}

export const TicketSchema = SchemaFactory.createForClass(Ticket);

// Geospatial index for position
TicketSchema.index({ position: '2dsphere' });

// Compound indexes for common queries
TicketSchema.index({ userId: 1, status: 1 });
TicketSchema.index({ licensePlate: 1, status: 1 });
TicketSchema.index({ agentId: 1, issuedAt: -1 });
TicketSchema.index({ issuedAt: -1 });
TicketSchema.index({ dueDate: 1, status: 1 });
