import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type TicketDocument = Ticket & Document;

export enum TicketReason {
  NO_SESSION = 'no_session',
  EXPIRED_SESSION = 'expired_session',
  OVERSTAYED = 'overstayed',
  WRONG_ZONE = 'wrong_zone',
}

export enum TicketStatus {
  PENDING = 'pending',
  PAID = 'paid',
  APPEALED = 'appealed',
  DISMISSED = 'dismissed',
  OVERDUE = 'overdue',
}

export enum PaymentMethod {
  WALLET = 'wallet',
  CARD = 'card',
  CASH = 'cash',
}

@Schema({ timestamps: true })
export class Ticket {
  @Prop({
    required: true,
    unique: true,
    uppercase: true,
    index: true,
  })
  ticketNumber: string;

  @Prop({
    type: Types.ObjectId,
    ref: 'ParkingMeter',
    required: true,
    index: true,
  })
  meterId: Types.ObjectId;

  @Prop({
    type: Types.ObjectId,
    ref: 'ParkingSession',
    required: false,
    index: true,
  })
  parkingSessionId?: Types.ObjectId;

  @Prop({
    type: Types.ObjectId,
    ref: 'User',
    required: false,
    index: true,
  })
  userId?: Types.ObjectId;

  @Prop({
    type: Types.ObjectId,
    ref: 'Agent',
    required: true,
    index: true,
  })
  agentId: Types.ObjectId;

  @Prop({ required: true, uppercase: true, index: true })
  licensePlate: string;

  @Prop({
    required: true,
    enum: TicketReason,
  })
  reason: TicketReason;

  @Prop({ required: true, min: 0 })
  fineAmount: number;

  @Prop({
    required: true,
    enum: TicketStatus,
    default: TicketStatus.PENDING,
    index: true,
  })
  status: TicketStatus;

  @Prop({ required: true })
  issuedAt: Date;

  @Prop({ required: true })
  dueDate: Date;

  @Prop({ required: false })
  paidAt?: Date;

  @Prop({
    required: false,
    enum: PaymentMethod,
  })
  paymentMethod?: PaymentMethod;

  @Prop({ required: false })
  notes?: string;

  @Prop({ type: [String], required: false })
  evidencePhotos?: string[];

  @Prop({ required: false })
  appealReason?: string;

  @Prop({ required: false })
  appealedAt?: Date;

  // Timestamps are auto-generated by mongoose
  createdAt?: Date;
  updatedAt?: Date;
}

export const TicketSchema = SchemaFactory.createForClass(Ticket);

// Compound indexes for common queries
TicketSchema.index({ userId: 1, status: 1 });
TicketSchema.index({ licensePlate: 1, status: 1 });
TicketSchema.index({ meterId: 1, status: 1 });
TicketSchema.index({ agentId: 1, issuedAt: -1 });
TicketSchema.index({ issuedAt: -1 });
TicketSchema.index({ dueDate: 1, status: 1 });
