import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { LicensePlate, LicensePlateSchema } from '../../shared/license-plate';

export type ParkingSessionDocument = ParkingSession & Document;

export enum ParkingSessionStatus {
  ACTIVE = 'active',
  COMPLETED = 'completed',
  EXPIRED = 'expired',
  CANCELLED = 'cancelled',
}

@Schema({ timestamps: true })
export class ParkingSession {
  @Prop({
    required: false,
    type: Types.ObjectId,
    ref: 'User',
    index: true,
  })
  userId?: Types.ObjectId;

  @Prop({
    type: Types.ObjectId,
    ref: 'ParkingZone',
    required: true,
    index: true,
  })
  zoneId: Types.ObjectId;

  @Prop({ required: true })
  zoneName: string;

  @Prop({
    type: {
      type: String,
      enum: ['Point'],
      default: 'Point',
    },
    coordinates: {
      type: [Number],
      required: true,
    },
  })
  location: {
    type: 'Point';
    coordinates: [number, number]; // [longitude, latitude]
  };

  /**
   * Structured license plate data
   */
  @Prop({ type: LicensePlateSchema })
  plate?: LicensePlate;

  /**
   * @deprecated Use plate.formatted instead
   * Kept for backward compatibility and indexing
   */
  @Prop({ required: true, uppercase: true, index: true })
  licensePlate: string;

  @Prop({ required: true })
  startTime: Date;

  @Prop({ required: true })
  endTime: Date;

  @Prop({ required: true, min: 1 })
  durationMinutes: number;

  @Prop({ required: true, min: 0 })
  amount: number;

  @Prop({
    required: true,
    enum: ParkingSessionStatus,
    default: ParkingSessionStatus.ACTIVE,
    index: true,
  })
  status: ParkingSessionStatus;

  /**
   * How the location was obtained
   * - gps_auto: Automatic GPS detection
   * - user_pin: User manually placed marker on map
   * - zone_centroid: Only zone selected (iOS fallback)
   * - unknown: Legacy or unspecified
   */
  @Prop({
    type: String,
    enum: ['gps_auto', 'user_pin', 'zone_centroid', 'unknown'],
    default: 'unknown',
  })
  locationSource: string;

  /**
   * Whether the provided coordinates fall within the selected zone boundaries
   * Used for location confidence assessment
   */
  @Prop({ type: Boolean, default: false })
  locationWithinZone: boolean;

  // Timestamps are auto-generated by mongoose
  createdAt?: Date;
  updatedAt?: Date;
}

export const ParkingSessionSchema =
  SchemaFactory.createForClass(ParkingSession);

// Geospatial index for location-based queries
ParkingSessionSchema.index({ location: '2dsphere' });

// Compound indexes for common queries
ParkingSessionSchema.index({ userId: 1, status: 1 });
ParkingSessionSchema.index({ userId: 1, createdAt: -1 });
ParkingSessionSchema.index({ licensePlate: 1, status: 1 });
ParkingSessionSchema.index({ zoneId: 1, status: 1 });
