import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type ParkingSessionDocument = ParkingSession & Document;

export enum ParkingSessionStatus {
  ACTIVE = 'active',
  COMPLETED = 'completed',
  EXPIRED = 'expired',
  CANCELLED = 'cancelled',
}

@Schema({ timestamps: true })
export class ParkingSession {
  @Prop({ required: true, index: true })
  userId: string;

  @Prop({ required: true })
  vehicleId: string;

  @Prop({ required: true, index: true })
  zoneId: string;

  @Prop({ required: true, uppercase: true })
  licensePlate: string;

  @Prop({ required: true })
  zoneName: string;

  @Prop({ required: true })
  startTime: Date;

  @Prop({ required: true })
  endTime: Date;

  @Prop({ required: true, min: 1 })
  durationMinutes: number;

  @Prop({ required: true, min: 0 })
  amount: number;

  @Prop({
    required: true,
    enum: ParkingSessionStatus,
    default: ParkingSessionStatus.ACTIVE,
    index: true,
  })
  status: ParkingSessionStatus;

  @Prop()
  ticketId?: string;

  // Timestamps are auto-generated by mongoose
  createdAt?: Date;
  updatedAt?: Date;
}

export const ParkingSessionSchema =
  SchemaFactory.createForClass(ParkingSession);

// Compound indexes for common queries
ParkingSessionSchema.index({ userId: 1, status: 1 });
ParkingSessionSchema.index({ userId: 1, createdAt: -1 });
ParkingSessionSchema.index({ licensePlate: 1, status: 1 });
